### ISSUE TITLE
[Question] use as a generic client

### ISSUE THREAD

**Issue by PascalSenn** [octokit/octokit.graphql.net#109]
Hello there. 

I really like the way this project is going. 
Will it be possible to use this client for any schema / endpoint or will it be just dedicated to github?

**Comment by StanleyGoldman** [comment]
Hey @PascalSenn. Thanks for checking our stuff out.

It is theoretically is possible to use the core of this to connect to any GraphQL library. 
It is something @grokys and I have thought about trying, but we figure we should get it production ready with one GraphQL schema before attempting others

_...it is something I'm tempted to try on some lonely weekend_ 😅

**Comment by grokys** [comment]
@PascalSenn: yes as @StanleyGoldman said, in theory the core of this library (`Octokit.GraphQL.Core`) should be able to be used on any GraphQL schema. We also have the `Generate` executable which can be fed any URL and will generate the entities for that schema.

However, we've not tried it on any GraphQL schema other than the GitHub one. I guess the first step would be to run that on your URL and see what happens ;)

**Comment by StanleyGoldman** [comment]
I'm gonna close out this question for now. We will revisit this.

**Comment by StanleyGoldman** [comment]
@PascalSenn I added #116 and #117 to help any developers start contributing to this library.
If you have any interest, please let us know what information you would need to help you.
