### ISSUE TITLE
What is the best way to use this with my own Github App?

### ISSUE THREAD

**Issue by MartinDawson** [octokit/octokit.graphql.net#118]
I want to access github data which this repository will let me do but I also want to store my own custom variables in a database with the data.

Is it best to fill out my own database with the queries returned by this GraphQL endpoint in the setup callback from Github APPs and then update my database in the webhooks (what I am doing at the moment with the REST API of Octokit).

Or is it better to query what I need dynamically?

What's the difference in using this library instead of my frontend just querying the GraphQL API v4 directly?

Also what's the benefit of using this over the Github Rest API, is it just that you can fetch what you want and reduce requests?

Thanks.

**Comment by StanleyGoldman** [comment]
Hey @MartinDawson. Thanks for checking our stuff out...

> I want to access github data which this repository will let me do but I also want to store my own custom variables in a database with the data.
> 
> Is it best to fill out my own database with the queries returned by this GraphQL endpoint in the setup callback from Github APPs and then update my database in the webhooks (what I am doing at the moment with the REST API of Octokit).
> 
> Or is it better to query what I need dynamically?

I really can't answer that for you as the answer really depends on your use case.
That said, please consider things like rate limits for the GitHub API. 

> What's the difference in using this library instead of my frontend just querying the GraphQL API v4 directly?

By frontend, I'm assuming you mean a frontend to a web application, probably JavaScript.
There really is no difference here, and again, this depends on your use case.

> Also what's the benefit of using this over the Github Rest API, is it just that you can fetch what you want and reduce requests?

This is where GraphQL really shines. In rest you are required to make multiple requests to get all the data you want. With GraphQL you are able to get the same data, a lot more customized, in fewer requests.

Sorry if I was not much help. Maybe @grokys can think of a few things that I haven't.
