### ISSUE TITLE
GraphQL INTERFACE TypeKind support in fragments

### ISSUE THREAD

**Issue by zgorcsos** [octokit/octokit.graphql.net#165]
Hi & Congrats! The API will be awesome & usefull!

But at this time does not support to use of fragments, if the target **GraphQL side TypeKind** is an **INTERFACE** in the definition of fragment.

For an simple example, i wrote this:
```csharp
var fragment = new Fragment<IRepositoryOwner, OwnerModel>("OwnerFragment", o =>
                            new OwnerModel()
                            {
                                Login = o.Login,
                                AvatarUrl = o.AvatarUrl(100),
                                Url = o.Url,
                            });
var query = new Query().Select(q => new
                {
                    repoOwner = q.Repository("octokit", "octokit.net")
                                    .Owner.Select(fragment).SingleOrDefault()
                }).Compile();
var result = connection.Run(query).Result;
```
Where the 'OwnerModel' is:
```csharp
public class OwnerModel
{
    public string Login { get; set; }
    public string Url { get; set; }
    public string AvatarUrl { get; set; }
}
```
(or similar simple class)

When the '_connection.Run_' (last line of the code above) is executed, an exception occured with this message:'_No such type IRepositoryOwner, so it can't be a fragment condition_'
This is a correct **GraphQL endpoint side error**, because the generated **GraphQL query string output** is:
```graphql
query {
  repoOwner: repository(owner: "octokit", name: "octokit.net") {
    owner {
      avatarUrl(size: 100)
      ...OwnerFragment
    }
  }
}
fragment OwnerFragment on IRepositoryOwner {
  login
  url
}
```  
Where the '**IRepositoryOwner**' is a bad name. There is '**RepositoryOwner**' correctly.
The direct source of error is here:
https://github.com/octokit/octokit.graphql.net/blob/339854b93552bd34b3275d0c1ea2794dfa852edd/Octokit.GraphQL.Core/Core/Syntax/FragmentDefinition.cs#L23

Because this uses simply .Net type name (_System.Type.Name_)here, that is: '**IRepositoryOwner**'.

> The type that implement this interface (StubIRepositoryOwner) is internal in the Generated modell in **RepositoryOwner.cs**. (And its name is different to GraphQL side type too...) So i can't use thats in the fragment's definition.

There is need an mapping betwen generated type name & GraphQL side name at this point... Or general support for type name mapping between **.Net** & **GraphQL** side? There is for general supporting all other potential naming convention differences such as different letter case or frequent word separation character (like underscore). Maybe is the use of an Attribute in generated type a good choise? 

But there is an another problem around here, because i would expect that as full correct GrapQL query string output:
```graphql
query {
  repoOwner: repository(owner: "octokit", name: "octokit.net") {
    owner {    
      ...OwnerFragment
    }
  }
}
fragment OwnerFragment on RepositoryOwner {
  login
  url
  avatarUrl(size: 100)
}
```

**Comment by grokys** [comment]
Hi, thanks for the report @zgorcsos! Indeed our interface support is very basic at the moment, and you may well find things broken (as you just have ;) ). I'm currently working on adding support for unions and interfaces are very similar, so I will try to get around to interfaces after this. I'll add your snippet as a test.

Thanks again, I'll let you know when this is fixed.

**Comment by zgorcsos** [comment]
Thx for your reply @grokys, i'm waiting to solution.
