### ISSUE TITLE
Question: Retrieving Repository Listings Efficiently

### ISSUE THREAD

**Issue by RickStrahl** [octokit/octokit.graphql.net#189]
I'm working on a project where we need to read the contents of a repository to effectively build an index from the content in a repository so that the content can be presented in different ways.

Thanks to help in another issue I figured out how I can use the GraphQL API to retrieve single level content easily via code. I wrote some helper code that loops through the folder structure one folder at a time:

```cs
        /// <summary>
        /// Retrieves all files in a given Github branch/path. Optionally
        /// allows recursively retrieving all content in child folders/trees.
        ///
        /// Note: child folders are lazy loaded so recursive action can  
        /// result in a lot of separate HTTP requests made to the server
        /// </summary>
        /// <param name="path">Branch and path to to start parsing on using `branch:path` syntax:
        /// Example: `master:` or `master:subpath\subpath2`</param>
        /// <param name="recursive">If true recurses any subpaths</param>
        /// <returns>List of Items optionally with child items</returns>
        public async Task<List<GithubFolderItem>> GetFolder(string path = "master:", bool recursive = true)
        {
            var productInformation = new ProductHeaderValue(ApiName, ApiVersion);

            var connection = new Connection(productInformation, _token);
            var query = new Query()
                .Repository(name: _repository, owner: _owner)
                .Object(expression: path)
                .Cast<Tree>()
                .Entries.Select(x => new GithubFolderItem
                {
                    Name = x.Name,
                    Type = x.Type,
                })
                .Compile();

            var entries = await connection.Run(query);


            foreach (var entry in entries)
            {
                entry.FullPath = path + entry.Name;

                if (!recursive || entry.Type != "tree")
                    continue;

                entry.Items = await GetFolder(entry.FullPath + "/");
            }

            return entries.ToList();
        }
```
[full code](https://gist.github.com/RickStrahl/e2a8ab089a02d2b79fbfe79cb2ba0ffe)

This works fine functionally wise but it's very slow and seems very inefficient. On even moderately sized repos this can take several minutes to process because each directory is a new request. I can probably optimize this a bit by running all same level folders simultaneously but that doesn't help with the overall request load.

From what I've read it appears that GraphQL doesn't support recursive requests so I wonder if it might be useful for some high level custom api to be available that can return just the file/folder info data for a repository. It would seem to me that that might be a common thing that people need to do and having to run so many individual requests is causing a ton of overhead both on Github and clients that have to serve that data.

I've seen quite a few requests for this sort of thing while searching (although with more specific search options).

Has any thought been given to provide some custom endpoint to provide file info for the entire repository even if the actual data returned is just Id, name, and path so that the detail can be pulled later...

**Comment by RickStrahl** [comment]
I guess the old API provides this functionality via Urls like this:

https://api.github.com/repos/RickStrahl/MarkdownMonster/git/trees/master?recursive=1

**Comment by jcansdale** [comment]
@RickStrahl,

Thanks for your follow up message. In GitHub for Visual Studio, we've ended up using a mixture of GraphQL/v4 and REST/v3 APIs. Unfortunately it isn't possible to use GraphQL for everything. 😢
