### ISSUE TITLE
Accessing Sponsorable data?

### ISSUE THREAD

**Issue by zcanann** [octokit/octokit.graphql.net#204]
`Query.sponsorsListing` does not exist in this library. In the documentatoin for the GraphQL api (https://developer.github.com/v4/query/), there is this warning:

`Query.sponsorsListing will be removed. Use Sponsorable.sponsorsListing instead. Removal on 2020-04-01 UTC.`

There does not appear to be a `Sponsorable` object either. Is this implemented yet?

**Comment by kfcampbell** [comment]
I believe this is fixed and the implementation is visible in Octokit.GraphQL/Model/SponsorsListing.cs. Please reopen if this is not the case!
