### ISSUE TITLE
Link Repository to Project Missing

### ISSUE THREAD

**Issue by isaacrlevin** [octokit/octokit.graphql.net#210]
Looking through Mutation, this is missing

https://developer.github.com/v4/mutation/linkrepositorytoproject/

**Comment by kfcampbell** [comment]
I believe this has been fixed. I see both a LinkRepositoryToProjectInput and LinkRepositoryToProjectPayload in Octokit.GraphQL/Model/LinkRepositoryToProjectInput.cs and Octokit.GraphQL/Model/LinkRepositoryToProjectPayload.cs respectively. Please reopen if this is not the case!
