### ISSUE TITLE
[Enhancement] Querying Sponsors

### ISSUE THREAD

**Issue by dansiegel** [octokit/octokit.graphql.net#228]
I currently have a query something like to get back sponsors though this would break down in the event that I ever reach more than 100 sponsors in any sponsorship level:

```graphql
query{
    viewer {
        login
        sponsorsListing {
            tiers(first: 10) {
                nodes {
                    name
                    monthlyPriceInDollars
                    adminInfo {
                        sponsorships(includePrivate: true, first: 100) {
                            nodes {
                                sponsor {
                                    id
                                    avatarUrl
                                    name
                                    login
                                    email
                                    location
                                }
                            }
                        }
                    }
                }
            }
        }
    }
 }
```

## Enhancement

It would be great if Octokit supported building out the appropriate query to get back the list of all sponsorship levels and sponsors.

### Proposal

There should be an easy to use built in API for working with Sponsorship Tiers and getting back Sponsors.

```cs
var query = new Query()
    .Viewer
    .Sponsors
    .Tiers(first: 10)
    ....
```

## Side Note

From looking at the GraphQL Explorer I do get a warning on this that the inner Sponsor node is deprecated and will be removed on October 1st. The suggested replacement `sponsorEntity` doesn't seem to support anything other than `__typename`. The docs do not match what the GraphQL Explorer shows so I'm not even sure if this is the correct query to use anymore... and I have not gotten any responses to support requests on the issue.

**Comment by vktr** [comment]
Just an FYI - the `sponsorEntity` is used as such,

```graphql
sponsorEntity {
  ... on User {
    login
  }
  ... on Organization {
    login
  }
}
```

**Comment by dansiegel** [comment]
thanks @vktr did not know `... on Entity` was a thing

**Comment by vktr** [comment]
> 
> 
> thanks @vktr did not know `... on Entity` was a thing

Me neither until recently :) It's called [inline fragments](https://graphql.org/learn/queries/#inline-fragments).
