### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by nerocui** [octokit/octokit.graphql.net#254]
I would love to use this one day, but it seems like this project is not active for a long time. Has it been abandoned?

**Comment by IvanJosipovic** [comment]
+1

**Comment by grokys** [comment]
I'm the originator of the project, but I'm no longer at GitHub and don't have time to maintain it I'm afraid.

**Comment by onein528** [comment]
@nickfloyd How do you generate schemes?

**Comment by nickfloyd** [comment]
> I can maintain this project for example generating schema regularly. @nickfloyd How about?

Hey @onein528, That would be amazing if you want to pick up generation on a regular cadence.  At least until we get to build some automation around all of that.  

Keep in mind that the generation is not at a 100% consistent generation state and you might run into some challenges.  See an example of a failure [here](https://github.com/octokit/octokit.graphql.net/actions/runs/1995803637). 

Please tag me for a review or anything if needed - we'll still follow the same release process until we get that refined as well.  

Thank you so much for 🤚 offering to step in here, it will definitely make an impact on helping to get contributions out the door for our awesome community! ❤️

**Comment by nickfloyd** [comment]
Closing out this issue given this has been moved to a couple of discussions: 
https://github.com/octokit/octokit.net/discussions/2499
https://github.com/octokit/octokit.net/discussions/2495
