### ISSUE TITLE
Rename default branch name 'master' with 'main'

### ISSUE THREAD

**Issue by 0x5bfa** [octokit/octokit.graphql.net#273]
## Description

As the title.

Octokit.net repo have already renamed to 'main'.

- [ ] Rename master to main
- [ ] Update all of the [workflows](https://github.com/octokit/octokit.graphql.net/tree/master/.github/workflows) to support this change
- [ ] Update any documentation that details master
- [ ] Post an [announcement](https://github.com/octokit/octokit.graphql.net/discussions/new) on the change (much like we did with [Ruby](https://github.com/octokit/octokit.rb/discussions/1455)
- [ ] Swap any existing PRs over to the new branch (if they did not automatically move)

## Motivation and Context

- https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch
- https://github.com/github/renaming

**Comment by nickfloyd** [comment]
@onein528 Thanks for getting this issue created 👍 ❤️

**Comment by Lamparter** [comment]
@0x5bfa this seems to have been done.

**Comment by 0x5bfa** [comment]
Thank you @Lamparter:)
