### ISSUE TITLE
[MAINT]: Project maintainance

### ISSUE THREAD

**Issue by 0x5bfa** [octokit/octokit.graphql.net#293]
### Describe the need

Hi I am @0x5bfa, who have contributed to this project with #269 & #270. I use this project in my app [FluentHub](https://github.com/FluentHub/FluentHub) and so we would like to maintain this project so that we can keep it up-to-date. Can I be a maintainer only for this repository so that I can fix and refactor quickly? @nickfloyd Before discuss here, I'd like to reach you out in Discord or Twitter DM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lamparter** [comment]
@0x5bfa if you want, we can fork this project and publish to NuGet ourselves....

**Comment by Lamparter** [comment]
Idk, just an idea. I don't know your conversation with nick floyd

**Comment by 0x5bfa** [comment]
I was thinking this isn't up-to-date whenever the new scheme is published and I wanted to make a CI to generate scheme everyday and improve infrastructure of this repo. I think, in that case, I probably should fork and use it as a sub module in our repo.

**Comment by Lamparter** [comment]
> I was thinking this isn't up-to-date whenever the new scheme is published and I wanted to make a CI to generate scheme everyday and improve infrastructure of this repo. I think, in that case, I probably should fork and use it as a sub module in our repo.

@0x5bfa Submodule is incredibly bad idea for maintenance. Just use automatic CI to publish to NuGet under @RiversideValley identity or as such.

**Comment by 0x5bfa** [comment]
lol I see, could you tell your suggestion in our discord?
